// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  window.SubView = (function(_super) {

    __extends(SubView, _super);

    SubView.name = 'SubView';

    function SubView() {
      return SubView.__super__.constructor.apply(this, arguments);
    }

    SubView.prototype.className = '.sub-view';

    return SubView;

  })(Backbone.View);

  describe("Backbone.Handlebars", function() {
    return describe("view helper", function() {
      return it("adds the sub-view element", function() {
        var TestView, view;
        TestView = (function(_super) {

          __extends(TestView, _super);

          TestView.name = 'TestView';

          function TestView() {
            return TestView.__super__.constructor.apply(this, arguments);
          }

          TestView.prototype.template = Handlebars.compile('{{view "SubView"}}');

          TestView.prototype.render = function() {
            return this.$el.html(this.template());
          };

          return TestView;

        })(Backbone.View);
        view = new TestView;
        view.render();
        return view.$('.sub-view').should.not.be["null"];
      });
    });
  });

}).call(this);
