// Generated by CoffeeScript 1.3.1
(function() {

  Handlebars.registerHelper('view', function(name, options) {
    var view, viewClass;
    viewClass = window[name];
    view = new viewClass;
    return new Handlebars.SafeString('<' + view.tagName + ' class="' + view.className + '"></' + view.tagName + '>');
  });

}).call(this);
