// Generated by CoffeeScript 1.3.1
(function() {

  Handlebars.registerHelper('view', function(name, options) {
    var parentView, view, viewClass;
    viewClass = window[name];
    view = new viewClass;
    parentView = options.data.view;
    parentView._toRender = view;
    return new Handlebars.SafeString('<div id="view-' + view.cid + '"></div>');
  });

  Backbone.View.prototype.renderTemplate = function(context) {
    var view;
    if (context == null) {
      context = {};
    }
    this.$el.html(this.template(context, {
      data: {
        view: this
      }
    }));
    view = this._toRender;
    view.render();
    return this.$("#view-" + view.cid).replaceWith(view.el);
  };

}).call(this);
